import 'package:flutter/material.dart';

final deptList = [
  'ANP - Anthropology',
  'ARC - Architecture',
  'BAN - Bangla',
  'BMB - Biochemistry and Molecular Biology',
  'BUS - Business Administration',
  'CEE - Civil and Environmental Engineering',
  'CEP - Chemical Engineering and Polymer Science',
  'CHE - Chemistry',
  'CSE - Computer Science and Engineering',
  'ECO - Economics',
  'EEE - Electrical and Electronic Engineering',
  'ENG - English',
  'FES - Forestry and Environmental Science',
  'FET - Food Engineering and Tea Technology',
  'GEB - Genetic Engineering and Biotechnology',
  'GEE - Geography and Environment',
  'IPE - Industrial and Production Engineering',
  'MAT - Mathematics',
  'MEE - Mechanical Engineering',
  'OCG - Oceanogrpahy',
  'PAD - Public Administration',
  'PHY - Physics',
  'PME - Petroleum and Mining Engineering',
  'PSS - Political Studies',
  'SCW - Social Work',
  'SOC - Sociology',
  'STA - Statisctics',
  'SWE - Software Engineering',
];
